# Generated by Django 6.0.7 on 2026-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_genre', models.CharField(max_length=40)),
                ('movie_year', models.IntegerField()),
            ],
        ),
    ]
